name: Apply

on:
  workflow_dispatch:

concurrency:
  group: tf
  cancel-in-progress: true

env:
  TF_LOG: ${{ secrets.TF_LOG || 'INFO' }}
  TF_VAR_gcp_resource_postfix: ${{ secrets.GCP_RESOURCE_POSTFIX }}
  TF_VAR_seed_sa_email_address: ${{secrets.SEED_SA_EMAIL_ADDRESS }}
  TF_IN_AUTOMATION: true
  TF_INPUT: false

permissions:
  id-token: write

jobs:
  security-scan:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Security scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: config
          trivy-config: trivy.yaml
          ignore-unfixed: false

  compliance-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.3055.0

  apply:
    runs-on: ubuntu-24.04

    needs:
      - compliance-scan
      - security-scan

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticating
        uses: google-github-actions/auth@v2.1.10
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.SEED_SA_EMAIL_ADDRESS }}
      - name: Setting up GCP environment
        uses: google-github-actions/setup-gcloud@v2.1.4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Init
        run: terraform init -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}"
      - name: Apply
        run: terraform apply -auto-approve
      - name: Show Terraform Output as Summary
        run: |
          {
            echo "### Terraform Apply Output";
            echo "\`\`\`";
            terraform output -no-color;
            echo "\`\`\`";
          }  > "${GITHUB_STEP_SUMMARY}"
