name: Script QA

on:
  push:
    paths:
      - "scripts/**"
  workflow_dispatch:

jobs:
  compliance-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: info
          scandir: "./scripts"
        env:
          SHELLCHECK_OPTS: -e SC1091
